name: Unit tests
env:
  FLUTTER_VERSION: '3.3.10'

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install app dependencies
        run: dart pub get
      - name: Analyze files
        run: dart analyze
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Run unit tests
        run: dart test test
